config/routes.rb
Rails.application.routes.draw do
  get 'sequences', to: 'sequences#index'
  get 'sequences/result', to: 'sequences#result'
  root 'sequences#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sequences_controller.rb
class SequencesController < ApplicationController
  def index
  end

  def result
    numbers = params[:numbers].split.map(&:to_i)

    segments = []
    current_segment = []
    longest_segment = []
    count = 0

    numbers.each do |num|
      if Math.sqrt(num) % 1 == 0
        current_segment << num
      else
        if current_segment.length > 1
          segments << { start: numbers.index(current_segment.first), end: numbers.index(current_segment.last) }
          count += 1
          if current_segment.length > longest_segment.length
            longest_segment = current_segment
          end
        end
        current_segment = []
      end
    end

    @result = {
      count: count,
      longest_segment: longest_segment,
      segments: segments
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Laba8</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sequences/index.html.erb
<%= form_tag sequences_result_path, method: :get do %>
  <label for="numbers">Введите числа через пробел:</label>
  <%= text_field_tag :numbers %><br>

  <%= submit_tag "Result" %>
<% end %>

app/views/sequences/result.html.erb
  <h2>Результаты:</h2>
  <p>Количество искомых отрезков: <%= @result[:count] %></p>
  <p>Самый длинный отрезок: <%= @result[:longest_segment] %></p>
  <p>Отрезки: </p>
  <table>
    <tr>
      <th>Начало</th>
      <th>Конец</th>
    </tr>
    <% @result[:segments].each do |segment| %>
      <tr>
        <td><%= segment[:start] %></td>
        <td><%= segment[:end] %></td>
      </tr>
    <% end %>
  </table>